package com.proyecto.kanban.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IssueAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssueAllPropertiesEquals(Issue expected, Issue actual) {
        assertIssueAutoGeneratedPropertiesEquals(expected, actual);
        assertIssueAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssueAllUpdatablePropertiesEquals(Issue expected, Issue actual) {
        assertIssueUpdatableFieldsEquals(expected, actual);
        assertIssueUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssueAutoGeneratedPropertiesEquals(Issue expected, Issue actual) {
        assertThat(actual)
            .as("Verify Issue auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssueUpdatableFieldsEquals(Issue expected, Issue actual) {
        assertThat(actual)
            .as("Verify Issue relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIssueUpdatableRelationshipsEquals(Issue expected, Issue actual) {
        assertThat(actual)
            .as("Verify Issue relationships")
            .satisfies(a -> assertThat(a.getLabels()).as("check labels").isEqualTo(expected.getLabels()))
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
